# Anero Mainnet Preset

MAX_COMMITTEES_PER_SLOT: 64
TARGET_COMMITTEE_SIZE: 128
MAX_VALIDATORS_PER_COMMITTEE: 4096
MIN_PER_EPOCH_CHURN_LIMIT: 128
CHURN_LIMIT_QUOTIENT: 65536

MIN_DEPOSIT_AMOUNT: 1000000000
MAX_EFFECTIVE_BALANCE: 32000000000
EFFECTIVE_BALANCE_INCREMENT: 1000000000

MIN_GENESIS_DELAY: 300
SECONDS_PER_SLOT: 12
SECONDS_PER_ETH1_BLOCK: 14
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256
SHARD_COMMITTEE_PERIOD: 256
ETH1_FOLLOW_DISTANCE: 2048

BLS_WITHDRAWAL_PREFIX: 0x00
GENESIS_FORK_VERSION: 0x00000000
BLS_SIGNING_DOMAIN_DISABLED: 0x00000000
